import { useEffect, useState } from "react";
import { NavLink, Navigate, Route, Routes } from "react-router-dom";
import { api } from "./api";
import Overview from "./pages/Overview";
import Traffic from "./pages/Traffic";
import Dwell from "./pages/Dwell";
import Visits from "./pages/Visits";
import Cameras from "./pages/Cameras";
import Calibration from "./pages/Calibration";
import Health from "./pages/Health";
import Settings from "./pages/Settings";

const NAV = [
  { to: "/overview", label: "Overview" },
  { to: "/traffic", label: "Traffic" },
  { to: "/dwell", label: "Dwell Time" },
  { to: "/visits", label: "Visits" },
  { to: "/cameras", label: "Cameras" },
  { to: "/calibration", label: "Calibration" },
  { to: "/health", label: "System Health" },
  { to: "/settings", label: "Settings" },
];

export default function App() {
  const [demoMode, setDemoMode] = useState(false);

  useEffect(() => {
    api.systemStatus().then((s) => setDemoMode(s.demo_mode)).catch(() => {});
    const id = setInterval(
      () => api.systemStatus().then((s) => setDemoMode(s.demo_mode)).catch(() => {}),
      30000
    );
    return () => clearInterval(id);
  }, []);

  return (
    <>
      <nav className="sidebar">
        <div className="brand">
          Operations <span>Vision</span>
        </div>
        {NAV.map((n) => (
          <NavLink
            key={n.to}
            to={n.to}
            className={({ isActive }) => `nav-link${isActive ? " active" : ""}`}
          >
            {n.label}
          </NavLink>
        ))}
      </nav>
      <main className="main">
        {demoMode && (
          <div className="demo-banner">
            DEMO MODE — data below is generated by the built-in simulator, not real cameras
          </div>
        )}
        <Routes>
          <Route path="/" element={<Navigate to="/overview" replace />} />
          <Route path="/overview" element={<Overview />} />
          <Route path="/traffic" element={<Traffic />} />
          <Route path="/dwell" element={<Dwell />} />
          <Route path="/visits" element={<Visits />} />
          <Route path="/cameras" element={<Cameras />} />
          <Route path="/calibration" element={<Calibration />} />
          <Route path="/health" element={<Health />} />
          <Route path="/settings" element={<Settings />} />
        </Routes>
      </main>
    </>
  );
}
