"""initial schema

Revision ID: 21f74c1ff1f9
Revises: 
Create Date: 2026-07-06 15:45:22.779301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21f74c1ff1f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_status',
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('last_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frames_received', sa.Integer(), nullable=False),
    sa.Column('frames_processed', sa.Integer(), nullable=False),
    sa.Column('processing_fps', sa.Float(), nullable=False),
    sa.Column('processing_latency_ms', sa.Float(), nullable=False),
    sa.Column('decode_errors', sa.Integer(), nullable=False),
    sa.Column('reconnect_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('camera_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_camera', sa.String(length=64), nullable=False),
    sa.Column('to_camera', sa.String(length=64), nullable=False),
    sa.Column('min_seconds', sa.Float(), nullable=False),
    sa.Column('expected_seconds', sa.Float(), nullable=False),
    sa.Column('max_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=True),
    sa.Column('visit_id', sa.String(length=32), nullable=True),
    sa.Column('track_id', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_events_type_ts', ['event_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_visit_id'), ['visit_id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('visits',
    sa.Column('visit_id', sa.String(length=32), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dwell_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry_camera', sa.String(length=64), nullable=True),
    sa.Column('current_camera', sa.String(length=64), nullable=True),
    sa.Column('current_zone', sa.String(length=64), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('handoff_count', sa.Integer(), nullable=False),
    sa.Column('cameras_observed', sa.Integer(), nullable=False),
    sa.Column('completion_reason', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('visit_id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_entry_time'), ['entry_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_status'), ['status'], unique=False)

    op.create_table('visit_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('camera_track_id', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_observations_visit_id'), ['visit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_observations_visit_id'))

    op.drop_table('visit_observations')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_status'))
        batch_op.drop_index(batch_op.f('ix_visits_entry_time'))

    op.drop_table('visits')
    op.drop_table('settings')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_visit_id'))
        batch_op.drop_index('ix_events_type_ts')
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))

    op.drop_table('events')
    op.drop_table('cameras')
    op.drop_table('camera_transitions')
    op.drop_table('camera_status')
    # ### end Alembic commands ###
